### ISSUE TITLE
Magic Lamp and Teaspoon are not friends ;)

### ISSUE THREAD

**Issue by rstudner** [crismali/magic_lamp#22]
So, if I have 250 tests (prior to using magic lamp).

I introduce magic lamp to the "first test".

It appears that the fixture magic lamp put in, "lasts forever".

I have:
```
<select id="orgSelector">
  <option>1</option>
  <option>2</option>
</select>
```
(to code-paraphrase).

So in mny FIRST test, it looks for $("#orgSelector").find('option') and sees there are 2 of them.

Then, 155 tests later, I have a fixture with
```
<select id="orgSelector">
  <option>1</option>
  <option>2</option>
...
  <option>17</option>
</select>
```

if I do r $("#orgSelector").find('option'), it finds that it has 2 options (even though the fixture in test 150 -- which is NOT magic lamp based, but just uses the jasmine test fixture loaded to pull a html file from disk) 
CLEARLY has 17).

Thoughts?

**Comment by rstudner** [comment]
To note, this is only true if I run "all of them" at once.  If I run JUST test 155, it works perfectly, finds 17, and passes.

**Comment by crismali** [comment]
@rstudner if you set a global `afterEach` and call `MagicLamp.clean()` it will ensure that there aren't leftover fixtures from Magic Lamp between tests. If you exclusively use MagicLamp fixtures this isn't a problem since `load` will clear out any existing fixtures before adding the new ones to the DOM. 

I think a big part of this issue though is that MagicLamp loads html with an id of `orgSelector`, leaves it behind, and then the other fixture loads html with the same id. Depending on what order they're in the DOM, jQuery will only find the first one since ids are supposed to be unique to the page.

**Comment by rstudner** [comment]
yeah.. I had just found it and was coming back to comment.

teaspoon/jasmine/mocha use "1 div" to hold their fixtures.. magic lamp was using it's own.. thus I literally had 2 of them on the page and the jquery selector was finding the other one.

my plan is to go 100% magic lamp of course.. just always the short term transitions / sellin' it hehe

Thanks again for the prompt reponse.
