### ISSUE TITLE
fixture loaded, inside document ready, $() returns undefined

### ISSUE THREAD

**Issue by proubits** [crismali/magic_lamp#23]
I use MagicLamp to load my rails view. However my $('selector') query returns undefined inside document ready or specially called after fixture loaded.

If fixture loaded with jasmine, spec runs without problem.

What would be the problem? Please help.

**Comment by crismali** [comment]
With out seeing the code, this is a little tricky to diagnose, but here are my thoughts:

* skip `$.ready` altogether - This is possible if you move your `javascript_include_tag` to the bottom of the `body` tag in your layout instead of leaving it in the `head` tag.
* stub `$.ready` so that the function passed to it is invoked immediately.
* There might be a subtle ordering issue - If you provide your function and the Jasmine Fixture and Magic Lamp versions of the test (paraphrases are fine), the issue might be more apparent.

**Comment by proubits** [comment]
Thanks. It looks like a subtle ordering issue. I tried a simplest test case. It works in both ways.

I noticed that the document ready triggered before fixture loaded. Is there any difference between fixture.load() and MagicLamp.load()?

**Comment by crismali** [comment]
Glad that helped :)

I'm not sure what difference there could be between them that would make `$(document).ready` behave differently. Generally, I never use `$(document).ready` and instead move my `javascript_include_tag` to the bottom of the page. This guarantees that the elements I need are on the page when my JavaScript executes and makes the JavaScript easier to test (i.e. I don't have to stub `ready`).
