### ISSUE TITLE
Trying to decipher an error

### ISSUE THREAD

**Issue by rstudner** [crismali/magic_lamp#24]
So i've been converting tests over happily.. I get errors doing magic_lamp/lint, they make sense, I fix them.

Now i'm getting an error I can't seem to decipher at all:
```
Error: NameError: undefined local variable or method `null' for #<NotificationsSettingsController:0x007ffd29f08588> 
```

It isn't complaining about a missing @ in the template etc (the standard error).. and I can't find any way to debug/breakpoint/make sense of the above error

I tried starting up rails in debug mode and setting breakpoints, but they don't even "stop" (in the actual controller code).  So, sort of at a loss haha.

Any hints/help would be appreciated :)

**Comment by rstudner** [comment]
was missing a variable in a loaded partial, but oddly wasn't showing "that" in the console output versus showing the error as coming from within the controller itself.

**Comment by crismali** [comment]
Should that `null` be `nil`? Or perhaps a string of `"null"`? That's my first approach.

If that didn't work I would use Pry to debug into the line above that error even if the code is located outside of the application (via `bundle open gem_name`). As a sort of smoke test I might try debugging into the MagicLamp fixture that's causing this problem itself and seeing how the controller responds to `null` in there. (Note: you'll want to provide the `name` option to the fixture so that way you skip debugging into the process where MagicLamp infers the fixture name).

If you provide the stack trace, what the fixture looks like, the template, and/or any controller methods that are called in the fixture that would help me get a better handle on what this issue is.

**Comment by rstudner** [comment]
Aha!

nil vs null.  I was getting a bunch of the info "for the magic lamp fixture" by pulling up the web page that had giant data-page-attributes= type of templated in JSON blobs.

Thus, of course, those used NULL vs NIL and I was pasting those into the fixture.

Dear Roger:  null is for javascript, nil is for ruby.

Thanks again for the help!
