### ISSUE TITLE
Form for with symbols breaks form rendering

### ISSUE THREAD

**Issue by daytonn** [crismali/magic_lamp#26]
```rb
= form_for :foo do
  ...
```

This form of `form_for` seems to break the routing. The above throws an error which can be fixed with:

```rb
= form_for :for, url: "" do
  ...
```

This is obviously not ideal.

**Comment by crismali** [comment]
Here's the current work around (works for Rails 4.0, 4.1, and 4.2):

```ruby
fixture do
  request.env["action_dispatch.request.path_parameters"] = { action: "index", controller: "orders" }
  render :edit
end
```

I don't really understand why these path parameters are necessary to us `form_for` with a symbol. Anyway, since Magic Lamp uses an `ActionDispatch::TestRequest` as the request and that in turn uses a sort of dummy env hash, you have to add the path parameters yourself.

I'd like to make this work out of the box but for now I'm not sure how to do so in way that isn't brittle and doesn't cause more trouble down the road.

**Comment by crismali** [comment]
Reopening this to remind me to try to make this work out of the box
