### ISSUE TITLE
missing example app

### ISSUE THREAD

**Issue by lazylester** [crismali/magic_lamp#29]
Thanks for magic_lamp, Michael. Looks like it's going to be a great help in my js testing.

In the readme, in last line of the the section titled "A few more examples", the link to "here's an example app" is broken. If that example app is still available, would it be possible to fix the link, please.
cheers, Les

**Comment by crismali** [comment]
@lazylester good catch. I've removed the link so people aren't confused for now, but I'd like to whip another example up soon.

**Comment by crismali** [comment]
Haven't gotten around to this but the fact that it hasn't come up in a while makes me think it's probably not necessary to have an example app in the repo. 

Also for people who are looking for a more detailed way to get started, I wrote a [blog post](https://www.devmynd.com/blog/setting-up-your-rails-5-app-for-javascript-testing/).

**Comment by jcquarto** [comment]
Another explanation of the lack of commentary:  people are looking at the gem, seeing no example app, and moving on.  :)   I don't mean this in a trite way but when there's no example app, and no open issues, and a small number of contributors and forkers, it's harder to justify the time to check it out.   "Hi, welcome to Cars-R-Us!  Please buy a car but No you cannot do a test drive!".

**Comment by crismali** [comment]
@jcquarto Right now I'm not sure what the value add is over what's already in the README.

**Comment by jcquarto** [comment]
were there an example app, even something as simple as a single resource scaffolded -- but fully magic_lamp tested -- there are several issues that others have posted about which the example app would presumably demonstrate. For example, i read one today about how to deal with `link_to()` url helper, the fellow had to re-write his code to not use `link_to` in order for magic_lamp tests to work. Then I read some more of the older issues and several more related things like that came up: stuff where there's either a disconnect in what magic_lamp is doing that examples would clear up or there's misconceptions from users as to what magic_lamp is trying to accomplish.

Or, here's the counter-question: what's the downside to providing the example app, esp since one used to exist anyway? It sounds like you believe it would be redundant, though as the creator of the gem you gotta figure you're the guy with the maximum knowledge of the gem and therefore possibly lesser qualified to determine what is sufficient examplage.

Love the idea for the gem!  There's just some loose ends around the edges that would impede it from being production-workhorse-ready
