### ISSUE TITLE
How do I use Magic Lamp to render cells?

### ISSUE THREAD

**Issue by erlandsona** [crismali/magic_lamp#40]
In our project we're using Cells to render html strings instead of the ActionView stack in a lot of cases... It works almost the same, pass in an instance that the cell treats as it's model and it will spit out the html. It's a ViewModel for Rails essentially.

The point being that we're not using controllers explicitly in all cases to render certain components of the app.

Is there a way to define fixtures that simply pass an instance variable into a cell and use that for the html instead of the ActionView render method?

In most cases we wouldn't even need a request / response cycle since the cells spit out stuff based on just a PORO. Some of them do need a current_user context though so we'll have to figure out how to get around that...

**Comment by crismali** [comment]
If you return a string in a `fixture` block, that string will become the fixture and the controller's `render` will never be called. So I'm not familiar with Cells, but just as an example:

```ruby
fixture(name: "user_cell") do
  user = User.new
  UserCell.new(user: user).render_or_to_html
end
```

Does that help? Let me know if you have more questions! :)

**Comment by erlandsona** [comment]
Wow thanks for the speedy response... I ended up testing it by returning just a simple "hello world" from the fixture which did work.

It made me realize though that MagicLamp doesn't seem to know anything about my Rails application. EG: Devise users, ActionView helpers included in the cells...

Granted that's probably my configuration or lack thereof. I'm curious how to provide those context specific setups to MagicLamp I suppose.

**Comment by crismali** [comment]
Devise can be a bit tricky. Since you're in the context of the controller when you're in a `fixture` block, you can change the session or whatever you need to do to trick Devise (it's been a while since I've had to do it). Alternatively, you could define a module that defines `current_user` an use the `:extend` option when declaring your `fixture` block to stub it out. That's usually what I end up doing.

I don't know very much about Cells or how it figures out which view helpers it should pick up on, but I would think you could either tell it about your controller or extend the cell instance with the appropriate helper. This [Stack Overflow post](http://stackoverflow.com/questions/33419821/rails-cells-4-access-devise-helpers) seems to indicate to me that some of the cells know about the controller so maybe something like this would work:

```ruby
fixture(controller: FoosController) do
  cell = FooCell.new
  cell.controller = self
  cell.render_or_to_html
end
```
