### ISSUE TITLE
Error with rails 5 url_helpers

### ISSUE THREAD

**Issue by jm96441n** [crismali/magic_lamp#43]
When we run the lint method to check the magic_lamp is properly rendering our templates, it is breaking on the url_helpers (link_to for a show page) by not grabbing the id that is passed to it. The page works fine when magic lamp is not involved. So the issue is why does the url helper think the id is nil? Sorry I'm still pretty new to this, thanks for your help!

Here's the error:
`Error: ActionView::Template::Error: No route matches {:action=>"show", :controller=>"metros", :id=>nil} missing required keys: [:id]`

Lamp file:
`MagicLamp.fixture(controller: CaboodlesController) do

      @metro = {"id": 4}
      render 'caboodles/testing'
end`

Routes:
`
get 'caboodles/testing/:id' => 'caboodles#testing', as: 'testing'
 resources :metros, only: :show
` 

Url_Helper in "/views/caboodles/testing.html.haml":
`=link_to 'Back to Metro, metro_path(id: @metro['id'])`

**Edit**
When we don't use link_to, but we use something like this:

`%a{href: "/metros/#{@metro['id']}"} Back to Metro`

the lint passes, and the view is properly rendered by magic lamp.

**Comment by crismali** [comment]
I think the issue is that when you do `@metro = { "id": 4 }`, `id` is actually a symbol instead of a string. 

```ruby
@metro = { "id": 4}
@metro["id"] #=> nil
@metro[:"id"] #=> 4
```

So you could change it to something like `@metro = { "id" => 4 }` or `@metro = { "id": 4 }.with_indifferent_access`. Then it should work with `link_to` and the path helper. Let me know if that fixes it or leaves you with a new error :)

**Comment by crismali** [comment]
What versions of Ruby are you using for the test and production environments?

**Comment by jm96441n** [comment]
using Rails 5 and Ruby 2.3.1 for both test and production environments

**Comment by crismali** [comment]
I can't reproduce that behavior in Ruby 2.3.1
```
$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
$ irb
irb(main):001:0> @metro = { "id": 4}
=> {:id=>4}
irb(main):002:0> @metro["id"]
=> nil
irb(main):003:0>  @metro[:"id"]
=> 4
```

How is `@metro` set in the production code?

**Comment by jm96441n** [comment]
@metro is being set from a parsed JSON object that is returned from our API. For testing purposes we are mocking the response. 
In the JSON file holding the object, metro is set this way:
`{
    "metro": { "id": 4}
}`

and in the controller:
`
response = HTTParty.get("api-address.com/metros/4.json")
response = JSON.parse(response.body)
@metro = response["metro"]

`

The error only comes when use the url helper in the view file, when I use an anchor tag and set the url that way the lint passes, and is rendered properly by magic lamp.


So this doesn't work:
`=link_to 'Back to Metro, metro_path(id: @metro['id'])`

But this does:
`%a{href: "/metros/#{@metro['id']}"} Back to Metro`

So it doesn't seem to be an  issue in the way that @metro is being set. Could it have to do with the response coming as JSON as opposed to an ActiveRecord object?

**Comment by crismali** [comment]
@jm96441n This appears to be string vs symbol key problem. The following works fine:

```ruby
json = %({ "metro": { "id": 4} })
response = JSON.parse(json)
@metro = response["metro"]
@metro["id"] #=> 4
```

which is pretty much the same as the following because `JSON.parse` always gives you string keys:

```ruby
response = { "metro" => { "id" => 4} }
@metro = response["metro"]
@metro["id"] #=> 4
```
but when you have it like this you end up with symbol keys:

```ruby
@metro = { "id": 4 }
# or more idiomatically
@metro = { id: 4 }
```

This difference in key types is why you ended up with different results in your test and production environments:

```ruby
# Symbol key
@metro = { :id => 4}
@metro[:id] #=> 4
@metro["id"] #=> nil

# String key
@metro = { "id" => 4}
@metro[:id] #=> nil
@metro["id"] #=> 4
```

So going back to your original fixture:

```ruby
MagicLamp.fixture(controller: CaboodlesController) do
  @metro = {"id": 4}
  render 'caboodles/testing'
end
```

You'd need to change `@metro` to have string keys like the results of `JSON.parse` in your production environment:

```ruby
MagicLamp.fixture(controller: CaboodlesController) do
  @metro = {"id" => 4}
  render 'caboodles/testing'
end
```

Let me know if that helps :)
