### ISSUE TITLE
How to get magic_lamp and factory_bot to work together?

### ISSUE THREAD

**Issue by richygit** [crismali/magic_lamp#45]
I've got magic_lamp working with a simple fixture and a mocha spec. However, I'd really like to DRY things up and use factory_bot to setup the fixture. I've tried requiring 'support/factory_bot' in different places to no avail.

How are you meant to do this?

`rake magic_lamp:lint` complains with:
```
Error: NoMethodError: undefined method 'create' for #<RainboxesController:0x00007fa153e50be0>
```

magic_lamp.rb

```ruby
MagicLamp.fixture(controller: RainboxesController) do
  create(:rainbox)
  render "index"
end
```

magic_lamp_config.rb

```ruby
#Simply load your helpers in the magic_lamp_config.rb file like so:
Dir[Rails.root.join("spec", "support", "magic_lamp_helpers/**/*.rb")].each { |f| load f }

require "database_cleaner"

MagicLamp.configure do |config|

  DatabaseCleaner.strategy = :transaction

  config.before_each do
    DatabaseCleaner.start
  end

  config.after_each do
    DatabaseCleaner.clean
  end
end
```

**Comment by crismali** [comment]
@richygit you'd need to `extend` your fixtures with the `FactoryBot::SyntaxMethods` module in order to use FactoryBot's `create` wherever you'd like, but I'd recommend against that.

Most of your controllers probably feature a `create` action so mixing FactoryBot in that way could lead to some weird bugs. I'd recommend just using `FactoryBot.create(...)` instead. 

Also, you may get some warnings either way since MagicLamp is set up to reload FactoryGirl and hasn't been updated to cover FactoryBot yet. That's a pretty easy change though so it should be done shortly.

Let me know if that helps or if you need any more help 👍
